### ISSUE TITLE
Make Ready for Public Release

### ISSUE THREAD

**Issue by andreasHausberger** [WhatTUDo/WhatTUDo#1]
# TODOs

- [x] Remove all secrets and private key information
- [x] Remove all comments not intended for public
- [x] Remove TypeKit/Adobe Font link. Find a free and similar font for the open source version
- [x] Sample data without TU Wien specific things
